/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionefasa;

import java.util.*;
import javax.swing.*;
import java.text.*;
import java.io.*;
import controlli.*;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.border.Border;
/*
 *
 * @author Fabio
 */
public class AssumiPersonale extends javax.swing.JFrame {
    private static ArrayList vetPersonale;
    private static Personale p;
    private static ArrayList vetBanca;
    private static Banca b;
    private static File users= new File("personale.dat");
    private static File banca= new File("banca.dat");
    
    public AssumiPersonale() {
        initComponents();

    }
    public AssumiPersonale(ArrayList vetPersonale, ArrayList vetBanca) {
        initComponents();

        this.vetPersonale = vetPersonale;
        this.vetBanca = vetBanca;
        specializzazione.addItem("Scegli specializzazione...");
        specializzazione.addItem("Scienziato livello 1");
        specializzazione.addItem("Scienziato livello 2");
        specializzazione.addItem("Bio-chimico");
        specializzazione.addItem("Astronomo");
        specializzazione.addItem("Capo scienziato");
        specializzazione.addItem("Direttore");
        specializzazione.addItem("Astrologo/a");
        specializzazione.addItem("Segretario/a");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codFisc = new javax.swing.JTextField();
        cogn = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        specializzazione = new javax.swing.JComboBox<>();
        dataNascita = new com.toedter.calendar.JDateChooser();
        residenza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ma = new javax.swing.JRadioButton();
        fe = new javax.swing.JRadioButton();
        indietro = new javax.swing.JButton();
        confRegistrazione = new javax.swing.JButton();
        cancella = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        via = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nCivico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        codIban = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cognome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data di nascita");

        codFisc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        codFisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codFiscActionPerformed(evt);
            }
        });

        cogn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        cogn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cognActionPerformed(evt);
            }
        });

        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Codice Fiscale");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Residenza");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Specializzazione");

        specializzazione.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        dataNascita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        residenza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        residenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residenzaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Sesso");

        ma.setBackground(new java.awt.Color(153, 153, 255));
        ma.setText("Maschio");
        ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maActionPerformed(evt);
            }
        });

        fe.setBackground(new java.awt.Color(153, 153, 255));
        fe.setText("Femmina");
        fe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feActionPerformed(evt);
            }
        });

        indietro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        indietro.setText("Back");
        indietro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        indietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroActionPerformed(evt);
            }
        });

        confRegistrazione.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confRegistrazione.setText("CONFERMA");
        confRegistrazione.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        confRegistrazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confRegistrazioneActionPerformed(evt);
            }
        });

        cancella.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancella.setText("Cancel");
        cancella.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        cancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Via");

        via.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        via.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("N. Civico");

        nCivico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        nCivico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nCivicoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Codice IBAN");

        codIban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Email");

        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(107, 107, 107)
                                    .addComponent(nCivico, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(via, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(47, 47, 47)
                                            .addComponent(residenza, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24)
                                .addComponent(codFisc, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ma)
                                        .addGap(18, 18, 18)
                                        .addComponent(fe))
                                    .addComponent(dataNascita, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(specializzazione, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cogn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Email)
                                    .addComponent(codIban, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(confRegistrazione, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(cancella, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(indietro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cogn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10)
                        .addComponent(jLabel2)
                        .addComponent(nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codIban, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codFisc, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ma)
                    .addComponent(fe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dataNascita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(residenza, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(via, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nCivico, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(specializzazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confRegistrazione, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancella, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indietro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codFiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codFiscActionPerformed
    
    }//GEN-LAST:event_codFiscActionPerformed

    private void cognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cognActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cognActionPerformed

    private void residenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residenzaActionPerformed

    private void maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maActionPerformed
        fe.setSelected(false);
    }//GEN-LAST:event_maActionPerformed

    private void feActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feActionPerformed
        ma.setSelected(false);
    }//GEN-LAST:event_feActionPerformed

    private void indietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroActionPerformed
        GestionePersonale g = new GestionePersonale(vetPersonale, vetBanca);
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_indietroActionPerformed

    private void cancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellaActionPerformed
        cogn.setText(null);
        nome.setText(null);
        codFisc.setText(null);
        ma.setSelected(false);
        fe.setSelected(false);
        residenza.setText(null);
        via.setText(null);
        nCivico.setText(null);
        specializzazione.setSelectedIndex(0);
        dataNascita.setCalendar(null);
        codIban.setText(null);
    }//GEN-LAST:event_cancellaActionPerformed

    private void confRegistrazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confRegistrazioneActionPerformed

        String cf, n, c, d, v, nc, r, s, fid, special, I, pass, dat, email;
        boolean vuoto = false;
        boolean avanti = true;
        double stipendio=0;
        int i;
        int l= vetPersonale.size();
        cf = convCodFisc();
        I = convCodIban();
        Date dataoggi= new Date();
        DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        email = Email.getText();
        if(!(valEmail(email))){
            vuoto=true;
        }
        if (ma.isSelected() == false && fe.isSelected() == false) {
            vuoto = true;
        }
        if (specializzazione.getSelectedIndex() == 0) {
            vuoto = true;
        }
        if (dataNascita.getCalendar() == null) {
            vuoto = true;
        }
        if(Controlli.controllanome(nome.getText()) || Controlli.controllanome(cogn.getText()) || Controlli.controllanome(residenza.getText()) || Controlli.controllanome(via.getText())){
            vuoto=true;
        }
        if(Controlli.controllacodice(cf)){
            vuoto=true;
        }
        if(Controlli.controllacodiceIban(I)){
            vuoto=true;
        }
        if(Controlli.controllacivico(nCivico.getText())){
            vuoto=true;
        }
        for(i=0; i<l && !vuoto;i++){
            p = (Personale) vetPersonale.get(i);
            if(cf.equals(p.codfisc)){
                vuoto=true;
                JOptionPane.showMessageDialog(this, "Codice Fiscale già registrato", "Attenzione", JOptionPane.ERROR_MESSAGE);
                codFisc.setText("");
            }
        }
        
        for(i=0; i<l && !vuoto; i++){
            b = (Banca) vetBanca.get(i);
                if(I.equals(b.iban)){
                    vuoto=true;
                    JOptionPane.showMessageDialog(this, "Codice Iban già registrato", "Attenzione", JOptionPane.ERROR_MESSAGE);
                    codIban.setText("");
            }
        }
        for(i=0; i<l && !vuoto; i++){
            p = (Personale) vetPersonale.get(i);
                if(email.equals(p.email)){
                    vuoto=true;
                    JOptionPane.showMessageDialog(this, "Email già registrata", "Attenzione", JOptionPane.ERROR_MESSAGE);
                    Email.setText("");
            }
        }
        DateFormat datadioggi =new SimpleDateFormat("dd-MM-yyyy") ;
        dat = datadioggi.format(dataNascita.getDate());
        if(Controlli.controllominorenne(df.format(dataoggi), dat)){
            vuoto=true;
            JOptionPane.showMessageDialog(this, "Il personale deve essere maggiorenne", "Attenzione", JOptionPane.ERROR_MESSAGE);
        }
        if (cogn.getText().isEmpty() || nome.getText().isEmpty() || codFisc.getText().isEmpty() || residenza.getText().isEmpty() || via.getText().isEmpty() || vuoto == true || codIban.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Non è possibile effettuare la registrazione, mancono alcune informazioni o sono errate", "Errore", JOptionPane.ERROR_MESSAGE);
            avanti = false;
        }
        if (avanti) {
            c = cogn.getText();
            n = nome.getText();
            d = df.format(dataNascita.getDate());
            v = via.getText();
            nc = nCivico.getText();
            r = residenza.getText();
            special = specializzazione.getSelectedItem().toString();
            if (ma.isSelected()) {
                s = ma.getText();
            } else {
                s = fe.getText();
            }
            email = Email.getText();
            fid = creaFid(n, c, d);
            pass =creaPassTemp();
            switch(specializzazione.getSelectedIndex()){
                case 1:
                    stipendio=1100;
                    break;
                case 2:
                    stipendio=1200;
                    break;
                case 3:
                    stipendio=1250;
                    break;
                case 4:
                    stipendio=1400;
                    break;
                case 5:
                    stipendio=1300;
                     break;
                case 6:
                    stipendio=1600;
                    break;
                case 7:
                    stipendio=1400;
                    break;
                case 8:
                    stipendio=1000;
                    break;
            }
            Personale p = new Personale(cf, n, c, d, s, v, nc, r, fid, special, pass, stipendio, email);
            Banca b = new Banca(I);
            vetPersonale.add(p);
            vetBanca.add(b);
            JOptionPane.showMessageDialog(this, "Registrazione Completata - FID : "+p.FId+" - Password Temporanea : "+p.pass, "", JOptionPane.INFORMATION_MESSAGE);
            cogn.setText("");
            nome.setText("");
            codFisc.setText("");
            ma.setSelected(false);
            fe.setSelected(false);
            residenza.setText("");
            via.setText("");
            nCivico.setText("");
            specializzazione.setSelectedIndex(0);
            dataNascita.setCalendar(null);
            codIban.setText("");
            Email.setText("");
        }
    }//GEN-LAST:event_confRegistrazioneActionPerformed

    private void viaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viaActionPerformed

    private void nCivicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nCivicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nCivicoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int d;
        int l=vetPersonale.size();
        if(users.exists() && banca.exists()){
            users.delete();
            banca.delete();
        }
        try{
            FileOutputStream f = new FileOutputStream("personale.dat");
            ObjectOutputStream o = new ObjectOutputStream(f);
            FileOutputStream b = new FileOutputStream("banca.dat");
            ObjectOutputStream a = new ObjectOutputStream(b);
            for(d=0; d<l; d++){
               o.writeObject((Personale)vetPersonale.get(d));
               o.flush();
               a.writeObject((Banca)vetBanca.get(d));
               a.flush();
               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Errore"+e.getMessage(), "Errore scrittura file", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssumiPersonale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssumiPersonale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssumiPersonale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssumiPersonale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssumiPersonale(vetPersonale,vetBanca).setVisible(true);
            }
        });
    }

    public static String creaFid(String n, String c, String d) {
        String f = "";
        int l= vetPersonale.size();
        boolean trovato=false;
        String charcters = "ABCDEFGHIJKMNOPQRSTUVWXYZ";
        int length = 4;
        Random rand = new Random();
        char[] text = new char[length];
        f += n.charAt(0);
        f += c.charAt(0);
        f += d.charAt(0);
        f += d.charAt(1);
        for (int i = 0; i < length; i++) {
            text[i] = charcters.charAt(rand.nextInt(charcters.length()));
        }
        for (int i = 0; i < text.length; i++) {
            f += text[i];
        }
        for(int i=0; i<l && !trovato; i++){
            p = (Personale) vetPersonale.get(i);
            if(f.equals(p.FId)){
                trovato = true;
                System.out.println("ciao");
            }
        }
        if(trovato){
            creaFid(n,c,d);
        }
        return f;
    }
    
     public static String creaPassTemp() {
        String f = "";
        String charcters = "ABCDEFGHIJKMNOPQRSTUVWXYZabcdefghijkmnopqesrtuvwxyz0123456789";
        int length = 8;
        Random rand = new Random();
        char[] text = new char[length];
        for (int i = 0; i < length; i++) {
            text[i] = charcters.charAt(rand.nextInt(charcters.length()));
        }
        for (int i = 0; i < text.length; i++) {
            f += text[i];
        }
        return f;
    }
    public String convCodFisc(){
        String cf = codFisc.getText().toUpperCase();
        return cf;
     }
    public String convCodIban(){
        String I = codIban.getText().toUpperCase();
        return I;
    }
    public static boolean valEmail(String input){
        String emailRegex = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$";
        Pattern emailPat = Pattern.compile(emailRegex,Pattern.CASE_INSENSITIVE);
        Matcher matcher = emailPat.matcher(input);
        return matcher.find();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JButton cancella;
    private javax.swing.JTextField codFisc;
    private javax.swing.JTextField codIban;
    private javax.swing.JTextField cogn;
    private javax.swing.JButton confRegistrazione;
    private com.toedter.calendar.JDateChooser dataNascita;
    private javax.swing.JRadioButton fe;
    private javax.swing.JButton indietro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton ma;
    private javax.swing.JTextField nCivico;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField residenza;
    private javax.swing.JComboBox<String> specializzazione;
    private javax.swing.JTextField via;
    // End of variables declaration//GEN-END:variables
}
