/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionefasa;


import java.io.*;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pantaleo.fabio
 */
public class GestioneRetribuzione extends javax.swing.JFrame {
    private static ArrayList vetPersonale;
    private static Personale p;
    private static ArrayList vetBanca;
    private static Banca b;
    private static File users = new File("personale.dat");
    private static File banca= new File("banca.dat");
    /**
     * Creates new form GestioneRetribuzione
     */
    public GestioneRetribuzione() {
        initComponents();
    }
    public GestioneRetribuzione(ArrayList vetPersonale,ArrayList vetBanca) {
        this.vetPersonale=vetPersonale;
        this.vetBanca=vetBanca;
        initComponents();
        visualizzaTab();
    }
    
    public void visualizzaTab(){
        int l=vetPersonale.size();
        int i;
        DefaultTableModel model=(DefaultTableModel) tabella.getModel();
        Object rowData[]=new Object[8];
        for(i=0; i<l;i++){
            p=(Personale) vetPersonale.get(i);
            b=(Banca) vetBanca.get(i);
            rowData[0]=p.cognome;
            rowData[1]=p.nome;
            rowData[2]=p.data;
            rowData[3]=p.codfisc;
            rowData[4]=b.iban;
            rowData[5] = p.ore;
            rowData[6]=p.figli;
            rowData[7]=p.stipendio;
            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabella = new javax.swing.JTable();
        ore = new javax.swing.JTextField();
        figli = new javax.swing.JTextField();
        Aggiorna = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        retribuzione = new javax.swing.JButton();
        home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabella.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tabella.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cognome", "Nome", "Data di Nascita", "Codice Fiscale", "Codice IBAN", "Ore lavorative extra", "N. figli", "Stipendio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabella.setColumnSelectionAllowed(true);
        tabella.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabellaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabellaFocusLost(evt);
            }
        });
        tabella.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabella);
        tabella.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabella.getColumnModel().getColumnCount() > 0) {
            tabella.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 648, 405));

        ore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(ore, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 66, 20));

        figli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(figli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 66, 20));

        Aggiorna.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Aggiorna.setText("Aggiorna");
        Aggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggiornaActionPerformed(evt);
            }
        });
        jPanel1.add(Aggiorna, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ore :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Figli : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel3.setText("Retribuzione Personale FASA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        retribuzione.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        retribuzione.setText("Retribuzione Personale");
        retribuzione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retribuzioneActionPerformed(evt);
            }
        });
        jPanel1.add(retribuzione, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 31));

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabellaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabellaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tabellaFocusGained

    private void tabellaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabellaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tabellaFocusLost

    private void tabellaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellaMouseClicked
        
        int row= tabella.getSelectedRow();
        ore.setText(tabella.getValueAt(row, 5).toString());
        figli.setText(tabella.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tabellaMouseClicked

    private void AggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggiornaActionPerformed
        int Ore, Figli;
        double sti;
         if(ore.getText().isEmpty() || figli.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "I campi sono vuoti o errati", "Errore", JOptionPane.ERROR_MESSAGE);
        }else{
            int row= tabella.getSelectedRow();
            tabella.setValueAt(Integer.parseInt(ore.getText()), row, 5);
            tabella.setValueAt(Integer.parseInt(figli.getText()), row, 6);
            Ore=Integer.parseInt(ore.getText());
            Figli=Integer.parseInt(figli.getText());
            sti=Double.parseDouble(tabella.getValueAt(row, 7).toString());
            sti=sti + (Figli*100) + (Ore*5);
            tabella.setValueAt(sti, row, 7);
        }
    }//GEN-LAST:event_AggiornaActionPerformed

    private void retribuzioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retribuzioneActionPerformed
        int l=vetBanca.size();
        int i;
        int row=0;
        for(i=0; i<l; i++){
            b= (Banca) vetBanca.get(i);
            b.saldo+=Double.parseDouble(tabella.getValueAt(row, 7).toString());
            System.out.println(""+b.saldo);
            row+=1;
        }
        
    }//GEN-LAST:event_retribuzioneActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        GestionePersonale g = new GestionePersonale(vetPersonale, vetBanca);
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int d;
        int l=vetPersonale.size();
        if(users.exists() && banca.exists()){
            users.delete();
            banca.delete();
        }
        try{
            FileOutputStream f = new FileOutputStream("personale.dat");
            ObjectOutputStream o = new ObjectOutputStream(f);
            FileOutputStream b = new FileOutputStream("banca.dat");
            ObjectOutputStream a = new ObjectOutputStream(b);
            for(d=0; d<l; d++){
               o.writeObject((Personale)vetPersonale.get(d));
               o.flush();
               a.writeObject((Banca)vetBanca.get(d));
               a.flush();
               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Errore"+e.getMessage(), "Errore scrittura file", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestioneRetribuzione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestioneRetribuzione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestioneRetribuzione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestioneRetribuzione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestioneRetribuzione(vetPersonale,vetBanca).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aggiorna;
    private javax.swing.JTextField figli;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ore;
    private javax.swing.JButton retribuzione;
    private javax.swing.JTable tabella;
    // End of variables declaration//GEN-END:variables
}
