/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionefasa;

import controlli.Controlli;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author Fabio
 */
public class GestioneBar extends javax.swing.JFrame {

    /**
     * Creates new form GestioneBar
     */
    private static ArrayList vetPersonale;
    private static ArrayList vetBanca;
    private static Banca b=null;
    private ImageIcon image1;
    private static int scelta=0;
    private static int index;
    private static File users= new File("personale.dat");
    private static File banca= new File("banca.dat");
    public GestioneBar() {
        initComponents();
    }
    
    public GestioneBar(ArrayList vetPersonale, ArrayList vetBanca, int index) {
        initComponents();
        this.vetPersonale = vetPersonale;
        this.vetBanca=vetBanca;
        this.index=index;
        generico.setVisible(false);
        jTF_prezzo.setVisible(false);
        jLabel_prezzo.setVisible(false);
        insCodiban.setVisible(false);
        codIban.setVisible(false);
        acquista.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        coffe = new javax.swing.JButton();
        hambu = new javax.swing.JButton();
        apple = new javax.swing.JButton();
        donut = new javax.swing.JButton();
        coca = new javax.swing.JButton();
        water = new javax.swing.JButton();
        generico = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        insCodiban = new javax.swing.JLabel();
        codIban = new javax.swing.JTextField();
        acquista = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_prezzo = new javax.swing.JLabel();
        jTF_prezzo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(700, 556));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 556));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coffe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/coffee.png"))); // NOI18N
        coffe.setBorderPainted(false);
        coffe.setContentAreaFilled(false);
        coffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeActionPerformed(evt);
            }
        });
        jPanel1.add(coffe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 30, 30));

        hambu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/burger.png"))); // NOI18N
        hambu.setBorderPainted(false);
        hambu.setContentAreaFilled(false);
        hambu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hambuActionPerformed(evt);
            }
        });
        jPanel1.add(hambu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 30, 30));

        apple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/apple.png"))); // NOI18N
        apple.setBorderPainted(false);
        apple.setContentAreaFilled(false);
        apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleActionPerformed(evt);
            }
        });
        jPanel1.add(apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 30, 30));

        donut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/doughnut.png"))); // NOI18N
        donut.setBorderPainted(false);
        donut.setContentAreaFilled(false);
        donut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donutActionPerformed(evt);
            }
        });
        jPanel1.add(donut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 30, 30));

        coca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/water (1).png"))); // NOI18N
        coca.setBorderPainted(false);
        coca.setContentAreaFilled(false);
        coca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocaActionPerformed(evt);
            }
        });
        jPanel1.add(coca, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 60, 130));

        water.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/water.png"))); // NOI18N
        water.setBorderPainted(false);
        water.setContentAreaFilled(false);
        water.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterActionPerformed(evt);
            }
        });
        jPanel1.add(water, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 60, 130));

        generico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        jPanel1.add(generico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 140, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/vending-machine (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 245, 267));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Benvenuto nella nostra mensa");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        insCodiban.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        insCodiban.setText("Inserire il codice Iban : ");
        jPanel1.add(insCodiban, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        codIban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(codIban, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 200, 20));

        acquista.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        acquista.setText("Acquista");
        acquista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        acquista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquistaActionPerformed(evt);
            }
        });
        jPanel1.add(acquista, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 70, 30));

        Home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Home.setText("Home");
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 70, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 350, 140));

        jLabel_prezzo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_prezzo.setText(" Prezzo : ");
        jLabel_prezzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel_prezzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 247, 60, 20));

        jTF_prezzo.setEditable(false);
        jTF_prezzo.setPreferredSize(new java.awt.Dimension(6, 21));
        jPanel1.add(jTF_prezzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donutActionPerformed
        jLabel_prezzo.setVisible(true);
        jTF_prezzo.setVisible(true);
        jTF_prezzo.setText("4.50");
        generico.setVisible(true);
        image1 = new ImageIcon(getClass().getResource("nut.png"));
        generico.setIcon(image1);
        scelta=1;
        insCodiban.setVisible(true);
        codIban.setVisible(true);
        acquista.setVisible(true);
    }//GEN-LAST:event_donutActionPerformed

    private void coffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeActionPerformed
        jLabel_prezzo.setVisible(true);
        jTF_prezzo.setVisible(true);
        jTF_prezzo.setText("0.80");
        generico.setVisible(true);
        image1 = new ImageIcon(getClass().getResource("cof.png"));
        generico.setIcon(image1);
        scelta=2;
        insCodiban.setVisible(true);
        codIban.setVisible(true);
        acquista.setVisible(true);
    }//GEN-LAST:event_coffeActionPerformed

    private void appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleActionPerformed
        jLabel_prezzo.setVisible(true);
        jTF_prezzo.setVisible(true);
        jTF_prezzo.setText("1");
        generico.setVisible(true);
        image1 = new ImageIcon(getClass().getResource("ap.png"));
        generico.setIcon(image1);
        scelta=3;
        insCodiban.setVisible(true);
        codIban.setVisible(true);
        acquista.setVisible(true);
    }//GEN-LAST:event_appleActionPerformed

    private void hambuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hambuActionPerformed
        jLabel_prezzo.setVisible(true);
        jTF_prezzo.setVisible(true);
        jTF_prezzo.setText("5");
        generico.setVisible(true);
        image1 = new ImageIcon(getClass().getResource("hambu.png"));
        generico.setIcon(image1);
        scelta=4;
        insCodiban.setVisible(true);
        codIban.setVisible(true);
        acquista.setVisible(true);
    }//GEN-LAST:event_hambuActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Menu m= new Menu(vetPersonale, vetBanca,index);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void waterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterActionPerformed
        jLabel_prezzo.setVisible(true);
        jTF_prezzo.setVisible(true);
        jTF_prezzo.setText("1.20");
        generico.setVisible(true);
        image1 = new ImageIcon(getClass().getResource("water.png"));
        generico.setIcon(image1);
        scelta=5;
        insCodiban.setVisible(true);
        codIban.setVisible(true);
        acquista.setVisible(true);
    }//GEN-LAST:event_waterActionPerformed

    private void cocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocaActionPerformed
        jLabel_prezzo.setVisible(true);
        jTF_prezzo.setVisible(true);
        jTF_prezzo.setText("1.50");
        generico.setVisible(true);
        image1 = new ImageIcon(getClass().getResource("water (1).png"));
        generico.setIcon(image1);
        scelta=6;
        insCodiban.setVisible(true);
        codIban.setVisible(true);
        acquista.setVisible(true);
    }//GEN-LAST:event_cocaActionPerformed

    private void acquistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquistaActionPerformed
        double costo=0;
        String I, dat;
        Date dataOggi = new Date();
        DateFormat datadioggi =new SimpleDateFormat("dd-MM-yyyy hh:mm:ss") ;
        dat = datadioggi.format(dataOggi);
        boolean trovato=false;  
        boolean avanti=true;
        boolean vuoto =false;
        int i;
        int l=vetBanca.size();
        I = convCodIban();
        System.out.println(""+I);
        if(Controlli.controllacodiceIban(I)){
            vuoto=true;
        }
        if (codIban.getText().isEmpty() || vuoto==true) {
            JOptionPane.showMessageDialog(this, "Inserisci un codice Iban corretto", "Errore", JOptionPane.ERROR_MESSAGE);
            avanti = false;
        }
        switch(scelta){
            case 1:
                costo=4.50;
                break;
            case 2:
                costo=0.80;
                break;
            case 3:
                costo=1;
                break;
            case 4:
                costo=5;
                break;
            case 5:
                costo=1.20;
                break;
            case 6:
                costo=1.50;
                break;
        }
        if(avanti){
            for(i=0; i<l && !trovato; i++){
                b= (Banca) vetBanca.get(i);
                if(I.equals(b.iban)){
                    trovato=true;
                    if(b.saldo<costo){
                        JOptionPane.showMessageDialog(this, "L'importo presente sul tuo conto bancario non è sufficiente per completare l'acquisto", "Errore", JOptionPane.ERROR_MESSAGE);
                    }else{
                        b.saldo= b.saldo-costo;
                        System.out.println(""+b.saldo);
                        b.LastPre = dat;
                        System.out.println(""+b.LastPre);
                    }
                }
            }
            if(!trovato){
                codIban.setText("");
            }
        }
    }//GEN-LAST:event_acquistaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int d;
        int l=vetPersonale.size();
        if(users.exists() && banca.exists()){
            users.delete();
            banca.delete();
        }
        try{
            FileOutputStream f = new FileOutputStream("personale.dat");
            ObjectOutputStream o = new ObjectOutputStream(f);
            FileOutputStream b = new FileOutputStream("banca.dat");
            ObjectOutputStream a = new ObjectOutputStream(b);
            for(d=0; d<l; d++){
               o.writeObject((Personale)vetPersonale.get(d));
               o.flush();
               a.writeObject((Banca)vetBanca.get(d));
               a.flush();
               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Errore"+e.getMessage(), "Errore scrittura file", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
    public String convCodIban(){
        String I = codIban.getText().toUpperCase();
        return I;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestioneBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestioneBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestioneBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestioneBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestioneBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton acquista;
    private javax.swing.JButton apple;
    private javax.swing.JButton coca;
    private javax.swing.JTextField codIban;
    private javax.swing.JButton coffe;
    private javax.swing.JButton donut;
    private javax.swing.JLabel generico;
    private javax.swing.JButton hambu;
    private javax.swing.JLabel insCodiban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_prezzo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_prezzo;
    private javax.swing.JButton water;
    // End of variables declaration//GEN-END:variables
}
