/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionefasa;

import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author pantaleo.fabio
 */
public class Menu extends javax.swing.JFrame {

    private static ArrayList vetPersonale = new ArrayList();
    private static ArrayList vetBanca = new ArrayList();
    private static int i;
    private static Personale p;
    private static boolean ac;
    private static File users = new File("personale.dat");
    private static File banca= new File("banca.dat");
    
    public Menu(){
        initComponents();
        if(users.exists()){
            try{
                FileInputStream f = new FileInputStream("personale.dat");
                ObjectInputStream o = new ObjectInputStream(f);
                FileInputStream b = new FileInputStream("banca.dat");
                ObjectInputStream a = new ObjectInputStream(b);
                
                while(true){
                    try{
                        vetPersonale.add((Personale)o.readObject());
                        vetBanca.add((Banca)a.readObject());
                    }catch(EOFException e){
                        break;
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Errore"+e.getMessage(), "Errore lettura file", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    public Menu(ArrayList vetPersonale, ArrayList vetBanca, int index, boolean ac) {
        initComponents();
        this.vetPersonale = vetPersonale;
        this.vetBanca = vetBanca;
        this.i = index;
        this.ac = ac;
    }
    public Menu(ArrayList vetPersonale, ArrayList vetBanca, int index) {
        initComponents();
        this.vetPersonale = vetPersonale;
        this.vetBanca = vetBanca;
        this.i = index;
    }
    public Menu(ArrayList vetPersonale, ArrayList vetBanca){
        initComponents();
        this.vetPersonale = vetPersonale;
        this.vetBanca = vetBanca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Email = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ModProfilo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        barmensa = new javax.swing.JButton();
        gestionepersonale = new javax.swing.JButton();
        login = new javax.swing.JButton();
        salvaEsci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(10, 164, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        Email.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        Email.setText("Email");
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 100, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/comet (2).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        ModProfilo.setBackground(new java.awt.Color(255, 255, 255));
        ModProfilo.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        ModProfilo.setText("MODIFICA PROFILO");
        ModProfilo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        ModProfilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModProfiloActionPerformed(evt);
            }
        });
        jPanel1.add(ModProfilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 280, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 2, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FASA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("   Fabio Aeronautics and Space Administration");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/earth-globe (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 130, -1));

        barmensa.setBackground(new java.awt.Color(255, 255, 255));
        barmensa.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        barmensa.setText("BAR-MENSA");
        barmensa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        barmensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barmensaActionPerformed(evt);
            }
        });
        jPanel1.add(barmensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 280, 50));

        gestionepersonale.setBackground(new java.awt.Color(255, 255, 255));
        gestionepersonale.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        gestionepersonale.setText("GESTIONE PERSONALE FASA");
        gestionepersonale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        gestionepersonale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionepersonaleActionPerformed(evt);
            }
        });
        jPanel1.add(gestionepersonale, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 280, 50));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 11)); // NOI18N
        login.setText("LOGIN");
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 100, 30));

        salvaEsci.setText("Salva ed esci");
        salvaEsci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        salvaEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaEsciActionPerformed(evt);
            }
        });
        jPanel1.add(salvaEsci, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/ImmagineDef.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionepersonaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionepersonaleActionPerformed
        
        String d;
        d="Direttore";
        if(ac){
            if(i==-1){
                GestionePersonale g = new GestionePersonale(vetPersonale, vetBanca);
                g.setVisible(true);
                this.dispose();
            }else{
                p=(Personale) vetPersonale.get(i);
                if((d.equals(p.special))){
                    GestionePersonale g = new GestionePersonale(vetPersonale, vetBanca);
                    g.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Non hai le crendeziali per quest' area", "Errore", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Devi prima effettuare il login", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_gestionepersonaleActionPerformed

    private void ModProfiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModProfiloActionPerformed
        if(ac){
            if(!(i==-1)){
                ModificaProfilo mf = new ModificaProfilo(vetPersonale, vetBanca, i);
                mf.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Hai effettuato l'accesso come admin", "", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Devi prima effettuare il login", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ModProfiloActionPerformed

    private void barmensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barmensaActionPerformed
        if(ac){
            if(!(i==-1)){
                GestioneBar mf = new GestioneBar(vetPersonale, vetBanca, i);
                mf.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Hai effettuato l'accesso come admin", "", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Devi prima effettuare il login", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_barmensaActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        Login l=new Login(vetPersonale,vetBanca,i,ac);
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void salvaEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaEsciActionPerformed
        int d;
        int l=vetPersonale.size();
        int r = JOptionPane.showConfirmDialog(null, "Vuoi salvare le modifiche?", "Salva ed esci", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(r == JOptionPane.YES_OPTION){
            if(users.exists() && banca.exists()){
                users.delete();
                banca.delete();
            }
            try{
                FileOutputStream f = new FileOutputStream("personale.dat");
                ObjectOutputStream o = new ObjectOutputStream(f);
                FileOutputStream b = new FileOutputStream("banca.dat");
                ObjectOutputStream a = new ObjectOutputStream(b);
                for(d=0; d<l; d++){
                    o.writeObject((Personale)vetPersonale.get(d));
                    o.flush();
                    a.writeObject((Banca)vetBanca.get(d));
                    a.flush();
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Errore"+e.getMessage(), "Errore scrittura file", JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        }else{
            if(r == JOptionPane.NO_OPTION){
                this.dispose();
            }
        }
    }//GEN-LAST:event_salvaEsciActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int d;
        int l=vetPersonale.size();
        if(users.exists() && banca.exists()){
            users.delete();
            banca.delete();
        }
        try{
            FileOutputStream f = new FileOutputStream("personale.dat");
            ObjectOutputStream o = new ObjectOutputStream(f);
            FileOutputStream b = new FileOutputStream("banca.dat");
            ObjectOutputStream a = new ObjectOutputStream(b);
            for(d=0; d<l; d++){
               o.writeObject((Personale)vetPersonale.get(d));
               o.flush();
               a.writeObject((Banca)vetBanca.get(d));
               a.flush();
               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Errore"+e.getMessage(), "Errore scrittura file", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        Email e = new Email(vetPersonale, vetBanca);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Email;
    private javax.swing.JButton ModProfilo;
    private javax.swing.JButton barmensa;
    private javax.swing.JButton gestionepersonale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JButton salvaEsci;
    // End of variables declaration//GEN-END:variables
}
