/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionefasa;

import controlli.Controlli;
import java.util.*;
import java.io.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.scene.paint.Color;
import javax.swing.*;
import javax.swing.border.Border;
/**
 *
 * @author Fabio
 */
public class ModificaProfilo extends javax.swing.JFrame {
    
    private static ArrayList vetPersonale;
    private static ArrayList vetBanca;
    private static Personale p;
    private static Banca b;
    private static int i;
    private static File users= new File("personale.dat");
    private static File banca= new File("banca.dat");
    /**
     * Creates new form ModificaProfilo
     */
    public ModificaProfilo() {
        initComponents();
    }
    
    public ModificaProfilo(ArrayList vetPersonale, ArrayList vetBanca, int i){
        initComponents();
        applica.setVisible(false);
        annulla.setVisible(false);
        confPass.setVisible(false);
        Rpass.setVisible(false);
        sti.setVisible(false);
        this.vetPersonale = vetPersonale;
        this.vetBanca = vetBanca;
        this.i=i;
        stampa();
    }
    
    private void stampa() {
        p = (Personale) vetPersonale.get(i);
        b = (Banca) vetBanca.get(i);
        nome.setText(p.nome);
        cognome.setText(p.cognome);
        codfisc.setText(p.codfisc);
        data.setText(p.data);
        sesso.setText(p.s);
        residenza.setText(p.residenza);
        via.setText(p.via);
        nCivico.setText(p.numerocivico);
        specializzazione.setText(p.special);
        fid.setText(p.FId);
        pass.setText(p.pass);
        CodIban.setText(b.iban);
        sti.setText(String.valueOf(p.stipendio));
        Email.setText(p.email);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        applica = new javax.swing.JButton();
        fid = new javax.swing.JTextField();
        jjlabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        specializzazione = new javax.swing.JTextField();
        Rpass = new javax.swing.JLabel();
        confPass = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cognome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        codfisc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sesso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        residenza = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        via = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nCivico = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        modifica = new javax.swing.JButton();
        annulla = new javax.swing.JButton();
        CodIban = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        sti = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Email.setEditable(false);
        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 184, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Email : ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionefasa/avatar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        applica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        applica.setForeground(new java.awt.Color(0, 153, 204));
        applica.setText("Applica");
        applica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        applica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicaActionPerformed(evt);
            }
        });
        jPanel1.add(applica, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 80, 30));

        fid.setEditable(false);
        fid.setBackground(new java.awt.Color(255, 255, 255));
        fid.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        fid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(fid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 88, 126, -1));

        jjlabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jjlabel12.setText("Fid:");
        jPanel1.add(jjlabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 91, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        pass.setEditable(false);
        pass.setBackground(new java.awt.Color(255, 255, 255));
        pass.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 143, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Specializzazione:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 139, -1, -1));

        specializzazione.setEditable(false);
        specializzazione.setBackground(new java.awt.Color(255, 255, 255));
        specializzazione.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        specializzazione.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(specializzazione, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 136, 120, -1));

        Rpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rpass.setText("Password : ");
        jPanel1.add(Rpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        confPass.setEditable(false);
        confPass.setBackground(new java.awt.Color(255, 255, 255));
        confPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        confPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(confPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 143, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 574, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        nome.setEditable(false);
        nome.setBackground(new java.awt.Color(255, 255, 255));
        nome.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 184, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cognome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        cognome.setEditable(false);
        cognome.setBackground(new java.awt.Color(255, 255, 255));
        cognome.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cognome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(cognome, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 184, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Codice Fiscale:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        codfisc.setEditable(false);
        codfisc.setBackground(new java.awt.Color(255, 255, 255));
        codfisc.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        codfisc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(codfisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 184, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Data di Nascita:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        data.setEditable(false);
        data.setBackground(new java.awt.Color(255, 255, 255));
        data.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Sesso:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        sesso.setEditable(false);
        sesso.setBackground(new java.awt.Color(255, 255, 255));
        sesso.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        sesso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(sesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 184, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Residenza:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        residenza.setEditable(false);
        residenza.setBackground(new java.awt.Color(255, 255, 255));
        residenza.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        residenza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(residenza, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 184, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Via:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        via.setEditable(false);
        via.setBackground(new java.awt.Color(255, 255, 255));
        via.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        via.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(via, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 184, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("N. civico:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        nCivico.setEditable(false);
        nCivico.setBackground(new java.awt.Color(255, 255, 255));
        nCivico.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nCivico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(nCivico, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 184, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 204));
        jLabel13.setText("PROFILO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        modifica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modifica.setForeground(new java.awt.Color(0, 153, 204));
        modifica.setText("Modifica");
        modifica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaActionPerformed(evt);
            }
        });
        jPanel1.add(modifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 80, 30));

        annulla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        annulla.setForeground(new java.awt.Color(0, 153, 204));
        annulla.setText("Annulla");
        annulla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        annulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaActionPerformed(evt);
            }
        });
        jPanel1.add(annulla, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 80, 30));

        CodIban.setEditable(false);
        CodIban.setBackground(new java.awt.Color(255, 255, 255));
        CodIban.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        CodIban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(CodIban, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 230, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Codice IBAN :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 100, -1));

        Home.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Home.setForeground(new java.awt.Color(0, 153, 204));
        Home.setText("Home");
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 60, 30));
        jPanel1.add(sti, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaActionPerformed
        modifica.setVisible(false);
        applica.setVisible(true);
        annulla.setVisible(true);
        confPass.setVisible(true);
        Rpass.setVisible(true);
        pass.setEditable(true);
        confPass.setEditable(true);
        residenza.setEditable(true);
        via.setEditable(true);
        nCivico.setEditable(true);
    }//GEN-LAST:event_modificaActionPerformed

    private void annullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaActionPerformed
        modifica.setVisible(true);
        annulla.setVisible(false);
        applica.setVisible(false);
        confPass.setVisible(false);
        Rpass.setVisible(false);
        pass.setEditable(false);
        confPass.setEditable(false);
        residenza.setEditable(false);
        via.setEditable(false);
        nCivico.setEditable(false);
        stampa();
    }//GEN-LAST:event_annullaActionPerformed

    private void applicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicaActionPerformed
        String cf, n, c, d, v, nc, r, s, I , passW , special, Fid, email, E;
        double stipendio;
        Border borde = BorderFactory.createLineBorder(java.awt.Color.red);
        Border border = BorderFactory.createLineBorder(java.awt.Color.DARK_GRAY);
        boolean vuoto = false;
        boolean avanti = true;
        int l= vetPersonale.size();
        if(!(pass.getText().equals(confPass.getText()))){
            vuoto=true;
            pass.setBorder(borde);
            confPass.setBorder(borde);
        }else{
            vuoto=false;
            pass.setBorder(border);
            confPass.setBorder(border);
        }
        if(Controlli.controllacivico(nCivico.getText())){
            vuoto=true;
        }
        if(Controlli.controllanome(residenza.getText()) || Controlli.controllanome(via.getText())){
            vuoto=true;
        }
        if (residenza.getText().isEmpty() || via.getText().isEmpty() || vuoto == true || nCivico.getText().isEmpty() || Email.getText().isEmpty() || pass.getText().isEmpty() || confPass.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "I campi sono vuoti o errati", "Errore", JOptionPane.ERROR_MESSAGE);   
            avanti = false;
        }
        if (avanti) {
            special = specializzazione.getText();
            Fid = fid.getText();
            c = cognome.getText();
            n = nome.getText();
            cf = codfisc.getText();
            d = data.getText();
            s = sesso.getText();
            email = Email.getText();
            v = via.getText();
            nc = nCivico.getText();
            r = residenza.getText();
            I = CodIban.getText();
            passW = pass.getText();
            stipendio = Double.parseDouble(sti.getText());
            Personale p = new Personale(cf, n, c, d, s, v, nc, r,Fid, special, passW,stipendio,email);
            Banca b = new Banca(I);
            vetPersonale.remove(i);
            vetBanca.remove(i);
            vetPersonale.add(i,p);
            vetBanca.add(i, b);
            JOptionPane.showMessageDialog(this, "Le modifiche sono state salvate con successo!", "", JOptionPane.INFORMATION_MESSAGE);
            modifica.setVisible(true);
            annulla.setVisible(false);
            applica.setVisible(false);
            confPass.setVisible(false);
            Rpass.setVisible(false);
            pass.setEditable(false);
            confPass.setEditable(false);
            codfisc.setEditable(false);
            nome.setEditable(false);
            cognome.setEditable(false);
            data.setEditable(false);
            CodIban.setEditable(false);
            residenza.setEditable(false);
            via.setEditable(false);
            nCivico.setEditable(false);
        }
    }//GEN-LAST:event_applicaActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Menu m= new Menu(vetPersonale, vetBanca);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int d;
        int l=vetPersonale.size();
        if(users.exists() && banca.exists()){
            users.delete();
            banca.delete();
        }
        try{
            FileOutputStream f = new FileOutputStream("personale.dat");
            ObjectOutputStream o = new ObjectOutputStream(f);
            FileOutputStream b = new FileOutputStream("banca.dat");
            ObjectOutputStream a = new ObjectOutputStream(b);
            for(d=0; d<l; d++){
               o.writeObject((Personale)vetPersonale.get(d));
               o.flush();
               a.writeObject((Banca)vetBanca.get(d));
               a.flush();
               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Errore"+e.getMessage(), "Errore scrittura file", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
    public static boolean valEmail(String input){
        String emailRegex = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$";
        Pattern emailPat = Pattern.compile(emailRegex,Pattern.CASE_INSENSITIVE);
        Matcher matcher = emailPat.matcher(input);
        return matcher.find();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaProfilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaProfilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaProfilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaProfilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificaProfilo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodIban;
    private javax.swing.JTextField Email;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Rpass;
    private javax.swing.JButton annulla;
    private javax.swing.JButton applica;
    private javax.swing.JTextField codfisc;
    private javax.swing.JTextField cognome;
    private javax.swing.JTextField confPass;
    private javax.swing.JTextField data;
    private javax.swing.JTextField fid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jjlabel12;
    private javax.swing.JButton modifica;
    private javax.swing.JTextField nCivico;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField residenza;
    private javax.swing.JTextField sesso;
    private javax.swing.JTextField specializzazione;
    private javax.swing.JTextField sti;
    private javax.swing.JTextField via;
    // End of variables declaration//GEN-END:variables
}
